<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AvalonEdit" Version="6.3.1.120" />
    <PackageVersion Include="FontAwesome6.Svg" Version="2.5.1" />
    <PackageVersion Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
    <PackageVersion Include="PhoenixmlDb.Xslt" Version="1.6.13" />
    <PackageVersion Include="PhoenixmlDb.XQuery" Version="1.6.12" />
    <PackageVersion Include="SaxonCS-HE" Version="13.0.0" />
    <PackageVersion Include="AngleSharp" Version="1.7.2" />
    <PackageVersion Include="System.Security.Cryptography.Xml" Version="10.0.10" />
  </ItemGroup>
</Project>